sudo: required
os:
  - linux
language: python
python:
  - 3.6
env:
  - TEST_SUITE=scripts/travis_tests.sh
  - TEST_SUITE=scripts/travis_test_truffle.sh
  - TEST_SUITE=scripts/travis_test_embark.sh
branches:
  only:
  - master
  - dev

install:
  - scripts/travis_install.sh

#script:
#  - $TEST_SUITE



